name: docker Build And Push

on:
  push:
    branches:
    - main
    - feature/*

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Login to docker
        uses: docker/login-action@v3.0.0
        with: 
          username: dareyregistry
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: dareyregistry/sample-cicd-docker:1.5.0